/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-04-07 16:25:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.*;
import java.util.*;
import model.*;

public final class newtopic_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n");
      out.write("<title>New Topic -BBS</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write('\r');
      out.write('\n');

User user = (User) request.getSession().getAttribute("user");
int boardpagenum =Integer.parseInt( request.getParameter("pn"));
ArrayList<String> topictitlelist = new ArrayList<String>();
TopicCheck tc =new TopicCheck();
tc.check();
topictitlelist=tc.getTopictitlelist();
ArrayList<Integer> topicidlist=tc.getTopicidlist();
long topicuid=0;
if (user != null) {
	        topicuid=user.getId();
	        System.out.println("newtopid获取发帖uid   "+topicuid);
}else{
	System.out.println("newtopic检测到未登录  ");
	request.setAttribute("msg", "请先登录");	
	System.out.println("用户未登录" );
	request.getRequestDispatcher("/error.jsp").forward(request,response);
} 

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container pagebody-top \">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-md-12\">\r\n");
      out.write("                <ul class=\"breadcrumb\" contenteditable=\"false\">\r\n");
      out.write("                    <li><a href=\"index.jsp\">Homepage</a> <span class=\"divider\"></span></li>\r\n");
      out.write("                    <li><a href=\"boardpage.jsp?pn=1\">BoardName</a> <span class=\"divider\"></span></li>\r\n");
      out.write("                    <li class=\"active\">New topic</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form class=\"form\" action=\"");
      out.print(request.getContextPath());
      out.write("/actions/dopost.jsp\" method=\"post\">\r\n");
      out.write("                    <fieldset>\r\n");
      out.write("                        <div id=\"legend\" class=\"\">\r\n");
      out.write("                            <legend class=\"\">New Topic</legend>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      <div class=\"input-group\">\r\n");
      out.write("                        <div class=\"input-group-btn\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-default dropdown-toggle\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">Category <span class=\"caret\"></span></button>\r\n");
      out.write("                            <ul class=\"dropdown-menu\">\r\n");
      out.write("                                <li><input type=\"radio\" id=\"ID\" name=\"NAME\" value=\"VALUE\"><label for=\"ID\">Category</label></li>\r\n");
      out.write("                                <li><input type=\"radio\" id=\"ID2\" name=\"NAME\" value=\"VALUE\"><label for=\"ID2\">Category2</label></li>\r\n");
      out.write("                                <li><input type=\"radio\" id=\"ID3\" name=\"NAME\" value=\"VALUE\"><label for=\"ID3\">Category3</label></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div><!-- /btn-group -->\r\n");
      out.write("\r\n");
      out.write("                        <input name=\"topictitle\" type=\"text\" class=\"form-control \" aria-label=\"...\" placeholder=\"New topic...\" style=\"width: 45%\">\r\n");
      out.write("                        <div class=\"col-md-5 \">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                        <div class=\"form-group\" >\r\n");
      out.write("\r\n");
      out.write("                                <textarea name=\"topicbody\" class=\"form-control\" rows=\"15\"  placeholder=\"Input text here\" style=\"width: 90%\"></textarea>\r\n");
      out.write("                         </div>\r\n");
      out.write("                        \r\n");
      out.write("                        <input type=\"hidden\" name=\"topicuid\" value=");
      out.print(topicuid );
      out.write(">\r\n");
      out.write("                        <input type=\"hidden\" name=\"boardpagenum\" value=");
      out.print(boardpagenum );
      out.write(">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-warning\" value=\"Post\"></button>\r\n");
      out.write("                        \r\n");
      out.write("                    </fieldset>\r\n");
      out.write("                </form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "foot.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
