/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.65
 * Generated at: 2016-04-07 16:24:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.TopicDao;
import org.apache.catalina.startup.UserConfig;
import java.util.*;
import java.sql.Connection;
import dao.ConnectionFactory;
import dto.*;
import model.*;
import java.util.ArrayList;

public final class topicpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->\r\n");
      out.write("<title>Topic Page -BBS</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "head.jsp", out, false);
      out.write(' ');
      out.write('\r');
      out.write('\n');
int topicid=Integer.parseInt(request.getParameter("tid"));
     int boardpage =Integer.parseInt( request.getParameter("pn")); //板块帖子页码
     
  ArrayList topictitlelist=new ArrayList();
  ArrayList topicbodylist=new ArrayList();
  ArrayList<Integer> topicuidlist=new ArrayList<Integer>();
  ArrayList<String> usravatarlist=new ArrayList<String>();
  ArrayList<Integer> topicreadcountlist=new ArrayList<Integer>();
  
  TopicCheck tc =new TopicCheck();
  UserCheck uc =new UserCheck();
  tc.check(); uc.check();
  topictitlelist=tc.getTopictitlelist();
  topicbodylist=tc.getTopicbodylist();
  topicuidlist=tc.getTopicuidlist();
  topicreadcountlist=tc.getTopicreadcountlist();
  usravatarlist=uc.getAvatarurllist();
long topicuid=topicuidlist.get(tc.getTopicidlist().indexOf(topicid));
  System.out.println("topicpage获取topicuid "+topicuid);
  System.out.println("发帖人"+  uc.getUsernamelist().get(uc.getUseridlist().indexOf((long) topicuid)));
  User user = (User) request.getSession().getAttribute("user");
  if(user!=null){
	  System.out.println("当前登录用户 "+user.getName()+"  userID="+user.getId());
  }

 if(session.getAttribute("tidmap")==null){
	 Map<Integer, String> tidmap = new HashMap<Integer, String>();
	 session.setAttribute("tidmap", tidmap);
 }
 Map<Integer, String> tidmap = (HashMap)session.getAttribute("tidmap");
if(tidmap.containsKey(topicid)==false){
	long readcount = (long)topicreadcountlist.get(tc.getTopicidlist().indexOf(topicid))+1;
	Topic topic =new Topic();  topic.setReadcount(readcount);    topic.setId((long)topicid);
	Connection conn =  ConnectionFactory.getInstance().makeConnection();
	TopicDao topicdao=new TopicDao();  topicdao.updatereadcount(conn, topic);

}
 tidmap.put(topicid, "exist");
 System.out.println("------------------------------访问人数="+topicreadcountlist.get(tc.getTopicidlist().indexOf(topicid))+"----------");
  

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container pagebody-top\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("    <div class=\"col-md-12 \">\r\n");
      out.write("        <ul class=\"breadcrumb \" contenteditable=\"false\">\r\n");
      out.write("            <li><a href=\"index.jsp\">Homepage</a> <span class=\"divider\"></span></li>\r\n");
      out.write("            <li><a href=\"boardpage.jsp?pn=1\">BoardName</a> <span class=\"divider\"></span></li>\r\n");
      out.write("            <li class=\"active\">Topic Name</li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <h2 ><a href=\"#\" class=\"button button-rounded button-width-small button-icon-txt-large\">Category</a> ");
      out.print(topictitlelist.get(tc.getTopicidlist().indexOf(topicid)) );
      out.write(" \r\n");
      out.write("                <small> At 2016-12-23 23:45</small>                                                                                                                   ");
 System.out.println("Topic title is "+topictitlelist.get(tc.getTopicidlist().indexOf(topicid))); 
      out.write("\r\n");
      out.write("            </h2>\r\n");
      out.write("\r\n");
      out.write("        <table class=\"table table-bordered table-responsive \">\r\n");
      out.write("            <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                \r\n");
      out.write("            </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td class=\"col-md-2 \" >\r\n");
      out.write("\r\n");
      out.write("        <img src=\"");
      out.print(usravatarlist.get(uc.getUseridlist().indexOf(topicuid)) );
      out.write("\"  class=\"IMG-ROUNDED img-thumbnail center-block img-responsive\" alt=\"Responsive image \">\r\n");
      out.write("                        <div style=\"margin-top: 10px    \"></div>");
System.out.println("Topic useravatarurl is "+usravatarlist.get(uc.getUseridlist().indexOf(topicuid)) ); 
      out.write("\r\n");
      out.write("                        <a href=\"#\" class=\"button   button-border button-small button-block button-rounded \" style=\"font-size: large\">");
      out.print( uc.getUsernamelist().get(uc.getUseridlist().indexOf(topicuid)));
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"margin-top: 10px;\" class=\"\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-xs btn-label\">Lv1</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success btn-xs btn-label\">Beginer <li class=\"icon-food\"></li></button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-xs btn-label\">Admin</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-info btn-xs btn-label\">Exp:23</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-xs btn-label\">BoardMaster</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success btn-xs btn-label\">OtherBadges</button>\r\n");
      out.write("                        </div>            \r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <table  class=\"table table-responsive table-bordered table-condensed\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-inverse btn-xs\">1st Floor</button>\r\n");
      out.write("                                    ");
if (user!=null && user.getId()==topicuid){
      out.write("\r\n");
      out.write("                                    \t\r\n");
      out.write("                                    \t <a href=\"/bbs/topicedit.jsp?tid=");
      out.print(topicid );
      out.write("&pn=");
      out.print(boardpage );
      out.write("\" type=\"button\" class=\"btn btn-default btn-xs\" style=\"margin-left: 15px\">Edit <span class=\"icon-pencil\"></span></button>\r\n");
      out.write("                                    <a  href=\"/bbs/actions/deletetopic.jsp?tid=");
      out.print(topicid );
      out.write("&pn=");
      out.print(boardpage );
      out.write("\" type=\"button\" class=\"btn btn-default btn-xs\">Delete <span class=\"icon-trash\"></span></a>\r\n");
      out.write("                                    <button class=\"button button-border button-primary button-pill button-tiny \">Share <span class=\"icon-share-alt\"></span></button>\r\n");
      out.write("                                    ");
	}else{
      out.write("\r\n");
      out.write("                                                                       \r\n");
      out.write("                                    <button class=\"button button-border button-primary button-pill button-tiny\"  style=\"margin-left: 15px \">Share <span class=\"icon-share-alt\"></span></button>\r\n");
      out.write("                                      ");
} 
      out.write("\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                         <p>\r\n");
      out.write("                             ");
      out.print(topicbodylist.get(tc.getTopicidlist().indexOf(topicid)) );
      out.write("\r\n");
      out.write("                         </p>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"margin-top: 200px;\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"signature\">\r\n");
      out.write("                            Signature\r\n");
      out.write("                        </div>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("           </tbody>\r\n");
      out.write("\r\n");
      out.write("            ");

             ReplyCheck rc =new ReplyCheck();  rc.check();
             ArrayList<String> replybodylist=new ArrayList<String>();
             ArrayList<Integer> replytidlist=new ArrayList<Integer>();
             ArrayList<Integer> replyuidlist=new ArrayList<Integer>();             
             replybodylist=rc.getReplybodylist();
             replyuidlist=rc.getReplyuidlist();
             replytidlist=rc.getReplytidlist();
             
             int replycount =0;  
             for(int i=1;i<replytidlist.size();i++){        	  
            	  if(replytidlist.get(i)==topicid){
            		  replycount++;
            	  }
             }
             
             System.out.println("当前帖子topicid="+topicid+" 回复数量获取值 "+replycount);
             
             if(replycount==0){
      out.write("\r\n");
      out.write("            \t                     </table>\r\n");
      out.write("  \r\n");
      out.write("  <nav class=\"text-center\">\r\n");
      out.write("                            <ul class=\"pagination  pagination-sm\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                                        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#\">1</a></li>\r\n");
      out.write("                                <li><a href=\"#\">2</a></li>\r\n");
      out.write("                                <li><a href=\"#\">3</a></li>\r\n");
      out.write("                                <li><a href=\"#\">4</a></li>\r\n");
      out.write("                                <li><a href=\"#\">5</a></li>\r\n");
      out.write("                                <li><a href=\"#\">6</a></li>\r\n");
      out.write("                                <li><a href=\"#\">7</a></li>\r\n");
      out.write("                                <li><a href=\"#\">8</a></li>\r\n");
      out.write("                                <li><a href=\"#\">9</a></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                                        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("            <div >\r\n");
      out.write("                <div class=\"well\">\r\n");
      out.write("\r\n");
      out.write("                    <form class=\"\" action=\"");
      out.print(request.getContextPath());
      out.write("/actions/doreply.jsp\" method=\"post\">\r\n");
      out.write("                        <fieldset>\r\n");
      out.write("                            <div class=\"form-group\" >\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <textarea class=\"form-control \" rows=\"5\"  placeholder=\"Input text here\" style=\"\" name=\"replybody\"></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           <input type=\"hidden\"  name=\"topictitle\" value=");
      out.print(topictitlelist.get(tc.getTopicidlist().indexOf(topicid)) );
      out.write(">\r\n");
      out.write("                           <input type=\"hidden\"  name=\"replytid\" value=");
      out.print(topicid );
      out.write(">\r\n");
      out.write("                           <input type=\"hidden\"  name=\"boardpagenum\" value=");
      out.print(boardpage );
      out.write(">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-warning\">Reply</button>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("            \t \r\n");
      out.write("            ");
 }else{
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("                  \r\n");
      out.write("                \t      <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th class=\" text-right\">\r\n");
      out.write("                        Replies：");
      out.print(replycount );
      out.write("\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th class=\"\"></th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                </thead>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <tbody>\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("                              \r\n");
      out.write("                   ");
  int floorcount=1; 
                   for(int j=1;j<replytidlist.size();j++){    
            	             if(replytidlist.get(j)==topicid){ 
            	            	 floorcount++;
            		            System.out.println("replybodylistget="+replybodylist.get(j));  
            		            int thisreplyid=rc.getReplyidlist().get(j);
            		            
      out.write("\r\n");
      out.write("            \t\t            <tr>\r\n");
      out.write("                <td>\r\n");
      out.write("\r\n");
      out.write("                <img src=\"");
      out.print(uc.getAvatarurllist().get(uc.getUseridlist().indexOf((long) replyuidlist.get(j))) );
      out.write("\"  class=\"IMG-ROUNDED img-thumbnail center-block img-responsive\" alt=\"Responsive image \">\r\n");
      out.write("                        <div style=\"margin-top: 10px    \"></div>\r\n");
      out.write("                        ");
System.out.println(uc.getAvatarurllist().get(uc.getUseridlist().indexOf((long) replyuidlist.get(j)))); 
      out.write("\r\n");
      out.write("                        <a href=\"#\" class=\"button   button-border button-small button-block button-rounded\" style=\"font-size: large\">");
      out.print(uc.getUsernamelist().get(uc.getUseridlist().indexOf((long) replyuidlist.get(j))));
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("                        <div style=\"margin-top: 10px;\" class=\"\">\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-primary btn-xs btn-label\">Lv1</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success btn-xs btn-label\">Beginer <li class=\"icon-food\"></li></button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-xs btn-label\">Admin</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-info btn-xs btn-label\">Exp:23</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-danger btn-xs btn-label\">BoardMaster</button>\r\n");
      out.write("                            <button type=\"button\" class=\"btn btn-success btn-xs btn-label\">OtherBadges</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("             <table  class=\"table table-responsive table-bordered table-condensed\">\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-inverse btn-xs\">Floor: ");
      out.print(floorcount );
      out.write("</button>\r\n");
      out.write("                                    ");
if (user!=null && user.getId()==(long) replyuidlist.get(j)){
      out.write("\r\n");
      out.write("                                    \r\n");
      out.write("  <a type=\"button\"   href=\"/bbs/replyedit.jsp?rid=");
      out.print(thisreplyid );
      out.write("&pn=");
      out.print(boardpage );
      out.write("&tid=");
      out.print(topicid );
      out.write("\"  class=\"btn btn-default btn-xs\" style=\"margin-left: 15px\">Edit <span class=\"icon-pencil\"></span></a>\r\n");
      out.write("                                    <button type=\"button\" class=\"btn btn-default btn-xs\">Delete <span class=\"icon-trash\"></span></button>\r\n");
      out.write("                                    <button class=\"button button-border button-primary button-pill button-tiny \">Share <span class=\"icon-share-alt\"></span></button>\r\n");
      out.write("                                    \r\n");
      out.write("                                        ");
}  else{ 
      out.write("\r\n");
      out.write("                                         <button class=\"button button-border button-primary button-pill button-tiny \" style=\"margin-left: 15px\">Share <span class=\"icon-share-alt\"></span></button>            \r\n");
      out.write("                                         \r\n");
      out.write("                                         ");
} 
      out.write("\r\n");
      out.write("                                         </div>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <p>\r\n");
      out.write("            \t\t             ");
      out.print(replybodylist.get(j)  );
      out.write("\r\n");
      out.write("            \t\t           \r\n");
      out.write("                    </p>\r\n");
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div style=\"margin-top: 200px;\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"signature\">\r\n");
      out.write("                            Signature <button type=\"button\" class=\"btn btn-default btn-xs  \"   style=\"margin-left: 15px\"> at 1230-23-23 23:34:23</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>        \r\n");
      out.write("            \t       ");
    }
                      } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </tbody>\r\n");
      out.write("        </table>\r\n");
      out.write("               \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("<nav class=\"text-center\">\r\n");
      out.write("                            <ul class=\"pagination  pagination-sm\">\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                                        <span aria-hidden=\"true\">&laquo;</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li><a href=\"#\">1</a></li>\r\n");
      out.write("                                <li><a href=\"#\">2</a></li>\r\n");
      out.write("                                <li><a href=\"#\">3</a></li>\r\n");
      out.write("                                <li><a href=\"#\">4</a></li>\r\n");
      out.write("                                <li><a href=\"#\">5</a></li>\r\n");
      out.write("                                <li><a href=\"#\">6</a></li>\r\n");
      out.write("                                <li><a href=\"#\">7</a></li>\r\n");
      out.write("                                <li><a href=\"#\">8</a></li>\r\n");
      out.write("                                <li><a href=\"#\">9</a></li>\r\n");
      out.write("                                <li>\r\n");
      out.write("                                    <a href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                                        <span aria-hidden=\"true\">&raquo;</span>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </nav>\r\n");
      out.write("  \r\n");
      out.write("            <div>\r\n");
      out.write("                <div class=\"well\">\r\n");
      out.write("                    <form name=\"replyform\" class=\"\" action=\"");
      out.print(request.getContextPath());
      out.write("/actions/doreply.jsp\" method=\"post\">\r\n");
      out.write("                        <fieldset>\r\n");
      out.write("                            <div class=\"form-group\" >\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <textarea   class=\"form-control \" rows=\"5\"  placeholder=\"Input text here\" style=\"\" name=\"replybody\" ></textarea>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                           <input type=\"hidden\"  name=\"topictitle\" value=");
      out.print(topictitlelist.get(tc.getTopicidlist().indexOf(topicid)) );
      out.write(">\r\n");
      out.write("                           <input type=\"hidden\"  name=\"replytid\" value=");
      out.print(topicid);
      out.write(">\r\n");
      out.write("                           <input type=\"hidden\"  name=\"boardpagenum\" value=");
      out.print(boardpage );
      out.write(">\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-warning\">Reply</button>\r\n");
      out.write("                        </fieldset>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("            \r\n");
      out.write("           ");
  }
      out.write("\r\n");
      out.write("             \r\n");
      out.write("                        \r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "foot.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
